### ISSUE TITLE
Now, how to make the board public?

### ISSUE THREAD

**Issue by saintly2k** [hrik2001/RikChan#5]
Well, I have set it up now on 127.0.0.1:5000 on my Linux server, but how can I:
* change the port?
* make it run on my public IP so I can make the board public?

I'd be really grateful, if you would help me out there.

**Comment by hrik2001** [comment]
I am sorry for replying late
Anyways so if you are running this webapp by using the `flask run` command, then it's better that you use something like gunicorn. Since gunicorn is actually a production server (used for actual hosting), while flask server is development server (used for local hosting for testing)

So if you want to host, set up gunicorn with flask, and in gunicorn settings you can do all of the above

**Comment by saintly2k** [comment]
Hey, no problem. Take your time for responding.
I did the exact thing you said yesterday already, I asked a friend and he told me to do the same thing you just did. So, sorry for even bothering you, I figured, that a Google would've told me the same, hahaha.
And great work, the Imageboard you made is great, I'm seeing forward to more updates and post pinning, etc.!
